export const CartConstant = {
    ADD_ITEM: "ADD_ITEM",
    ADD_ITEM_ERROR: "ADD_ITEM_ERROR",
    REMOVE_ITEM: "REMOVE_ITEM",
    REMOVE_ITEM_ALL: "REMOVE_ITEM_ALL",
    INCREASE_QUANTITY: "INCREASE_QUANTITY",
    DECREASE_QUANTITY: "DECREASE_QUANTITY",
    FETCH_CART_ITEMS_START: "FETCH_CART_ITEMS_START",
    FETCH_CART_ITEMS: "FETCH_CART_ITEMS",
    FETCH_CART_ITEMS_SUCCESS: "FETCH_CART_ITEMS_SUCCESS",
    FETCH_CART_ITEMS_ERROR: "FETCH_CART_ITEMS_ERROR"
}