export const ProductActions = {
    FETCH_PRODUCTS: "FETCH_PRODUCTS",
    PRODUCT_DETAIL: "PRODUCT_DETAIL",
    REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTED_PRODUCT",
    FILTERED_PRODUCT: "FILTERED_PRODUCT",
    RESET_FILTER: "RESET_FILTER"
}