export const TodoConstants = {
    FETCH_ALL_TODOS: "FETCH_ALL_TODOS",
    FETCH_ALL_TODOS_SUCCESS: "FETCH_ALL_TODOS_SUCCESS",
    FETCH_ALL_TODOS_ERROR: "FETCH_ALL_TODOS_ERROR",
    ADD_TODO: "ADD_TODO",
    DELETE_TODO: "DELETE_TODO",
    UPDATE_TODO: "UPDATE_TODO",
    UPDATE_TODO_START: "UPDATE_TODO_START",
    UPDATE_TODO_END: "UPDATE_TODO_END"
}